export enum ActionType {
  ADD_STUDENT = "ADD_STUDENT",
  DELETE_STUDENT = "DELETE_STUDENT",
  UPDATE_STUDENT = "UPDATE_STUDENT",
  GET_STUDENT = "GET_STUDENT",
  GET_STUDENTS = "GET_STUDENTS",
  STUDENT_ERROR = "STUDENT_ERROR",
}
